### ISSUE TITLE
Few issues running out of the box

### ISSUE THREAD

**Issue by ghost** [nikhilkoduri-searce/terraform-k8s-gce#1]
Firstly, i got _a lot_ of these issues

> Error: Module not found
> The module address "terraform-worker" could not be resolved.
> If you intended this as a path relative to the current module, use
"./terraform-worker" instead. The "./" prefix indicates that the address is a
relative filesystem path.

so i added "./" to all the module `source` values. Then I got lost of these errors:

> Error: Invalid version constraint
> Cannot apply a version constraint to module "worker-mig" (at
terraform-worker/main.tf:73) because it has a relative local path.

Not sure why you are versioning a local module (or even how to specify the version in the sub module).

using:

> Terraform v0.12.6
> + provider.google v2.6.0
> + provider.google-beta v2.6.0
> + provider.local v1.2.2
> + provider.null v2.1.2
> + provider.random v2.1.2
> + provider.template v2.1.2
> + provider.tls v2.0.1

note: i'm following the setup [here](https://medium.com/searce/kubernetes-deployment-on-google-compute-engine-using-terraform-8d6075cf4d3f) and the `terraform-provider-k8s` is not in the above list :(

I was also getting this error:

> Error: failed to load provider "k8s": Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

which went away when I swtiched to terrafrom 11. You should note somewhere in the Readme.md that this only works in terraform 11.

Now I'm getting these errors when I try to `terraform plan`

> Error: k8s_manifest.cluster_autoscaler_deploy: : invalid or unknown key: kind
> Error: k8s_manifest.cluster_autoscaler_deploy: : invalid or unknown key: name
> Error: k8s_manifest.cluster_autoscaler_deploy: : invalid or unknown key: namespace
> Error: k8s_manifest.cluster_autoscaler_deploy: : invalid or unknown key: status
> ...

I guess still a problem with the provider. That provider seems to have stopped development and is not taking issues so its not a good idea to use it for future work.

**Comment by nikhil313** [comment]
'terraform-provider-k8s' is a custom terraform provider that we have forked and played around with you can find the same repository here [github.com/searce-engineering/terraform-provider-k8s](https://github.com/searce-engineering/terraform-provider-k8s)
Im sure your issues will be resolved using this.

**Comment by nikhil313** [comment]
Regarding the module not found error, The terraform-worker module is present in the folder placed in root directory. Depending on the Operating system file structure that you are using you should replace the path accordingly. If not then you can even use the folder in this github repository as the source. thanks

**Comment by bskrishna60** [comment]
When i click hit the command terraform init this is the below error I'm facing. 

Pretty new to terraform, please help!

terraform init
Initializing modules...
- module.master-1
- module.nat
- module.gcp-worker-core
- module.gcp-worker-gpu
- module.kubernetes_dashboard
- module.metric_server
- module.cluster-autoscalar
- module.prometheus
- module.gcp-worker-gpu.worker-mig
- module.master-1.master-instance
- module.nat.nat-gateway
- module.gcp-worker-core.worker-mig

Initializing provider plugins...
failed to read provider plugin /bin/terraform-provider-k8s: open /bin/terraform-provider-k8s: no such file or directory

**Comment by searceinc** [comment]
@bskrishna60 You need to download go and download the k8s-provider using the go get command. Please refer the Readme of the github for the precise steps. 
If you need a detailed walkthough please refer the following blog:
https://medium.com/searce/kubernetes-deployment-on-google-compute-engine-using-terraform-8d6075cf4d3f

**Comment by bskrishna60** [comment]
Hi, thanks for getting back.

I've already installed go and downloaded k8 provider using the command go get -u github.com/searce-engineering/terraform-provider-k8s

go version installed is as follows-
go version go1.10.3 gccgo (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0 linux/amd64

**Comment by searceinc** [comment]
@bskrishna60 Hey, you would also need to set the provider location int the '~/.terraformrc' file.
That would do the trick.

**Comment by bskrishna60** [comment]
We've already followed the document and created the file .terraformrc file and provided the path as mentioned in the document i.e, providers { k8s = "$GOPATH/bin/terraform-provider-k8s" }

Could you let us know if any changes need to be made ?

FYI, I'm using a ubuntu machine

thanks again for the quick reply.
